server:
  port: 8721
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      filters: stat,wall,log4j2
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        allow:
        deny:
        login-username: admin
        login-password: 123456
    name: defaultDataSource
    url: jdbc:mysql://www.kanade.cn:3306/test?serverTimezone=GMT%2B8
    username: root
    password: root
  flyway:
    clean-disabled: true
    baseline-on-migrate: true
    schemas: flyway
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl